/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as HotlineRouteImport } from './routes/hotline'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HospitalOnboardingRouteImport } from './routes/hospital-onboarding'
import { Route as HospitalDashboardRouteImport } from './routes/hospital-dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HotlineRoute = HotlineRouteImport.update({
  id: '/hotline',
  path: '/hotline',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalOnboardingRoute = HospitalOnboardingRouteImport.update({
  id: '/hospital-onboarding',
  path: '/hospital-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDashboardRoute = HospitalDashboardRouteImport.update({
  id: '/hospital-dashboard',
  path: '/hospital-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/hospital-onboarding': typeof HospitalOnboardingRoute
  '/hospitals': typeof HospitalsRoute
  '/hotline': typeof HotlineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/hospital-onboarding': typeof HospitalOnboardingRoute
  '/hospitals': typeof HospitalsRoute
  '/hotline': typeof HotlineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/hospital-onboarding': typeof HospitalOnboardingRoute
  '/hospitals': typeof HospitalsRoute
  '/hotline': typeof HotlineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/hospital-dashboard'
    | '/hospital-onboarding'
    | '/hospitals'
    | '/hotline'
    | '/reset-password'
    | '/settings'
    | '/sos'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/hospital-dashboard'
    | '/hospital-onboarding'
    | '/hospitals'
    | '/hotline'
    | '/reset-password'
    | '/settings'
    | '/sos'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/hospital-dashboard'
    | '/hospital-onboarding'
    | '/hospitals'
    | '/hotline'
    | '/reset-password'
    | '/settings'
    | '/sos'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  HospitalDashboardRoute: typeof HospitalDashboardRoute
  HospitalOnboardingRoute: typeof HospitalOnboardingRoute
  HospitalsRoute: typeof HospitalsRoute
  HotlineRoute: typeof HotlineRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SosRoute: typeof SosRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotline': {
      id: '/hotline'
      path: '/hotline'
      fullPath: '/hotline'
      preLoaderRoute: typeof HotlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-onboarding': {
      id: '/hospital-onboarding'
      path: '/hospital-onboarding'
      fullPath: '/hospital-onboarding'
      preLoaderRoute: typeof HospitalOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-dashboard': {
      id: '/hospital-dashboard'
      path: '/hospital-dashboard'
      fullPath: '/hospital-dashboard'
      preLoaderRoute: typeof HospitalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  HospitalDashboardRoute: HospitalDashboardRoute,
  HospitalOnboardingRoute: HospitalOnboardingRoute,
  HospitalsRoute: HospitalsRoute,
  HotlineRoute: HotlineRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SosRoute: SosRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
